# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CRUDTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CRUDTest
pod 'Alamofire', '~> 5.2'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
end
